language: python
python:
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
# command to install dependencies
install: "pip install -e ."
#  - "pip install -r requirements.txt"
#  - "pip install pytest"
# command to run tests
script: tox